name: chat-db

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5050:5050"
    env_file: ./backend/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
